apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: sample-app
spec:
  project: default

  source:
    repoURL: git@github.com:quannt24/code-monkey-argocd-ops.git
    targetRevision: HEAD
    path: sample-app
    helm:
      valueFiles:
        - local-secret.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
